### PR TITLE
Replaces fors with forEaches and cleans up tabs

### PR DESCRIPTION
**Pull request by tainacaetano**
This PR:

- Cleans up some lost tabs and weird indentation;
- Replaces for loops with Array.forEach;
- Renames a few things that were hard(er) to get on the first read.

### CODE REVIEW

**Comment by chinaowl** [comment]
Code looks good to me.

However, since we want to focus on delivering new functionality (integration with ActionKit as a first step), I think it might be good to merge this with the `refactor` branch instead.

@tainacaetano can you make a new PR?

@pamo @n-zeplo

**Comment by tainacaetano** [comment]
I'm good with making a new PR, but from the looks of it the 350 guys would rather have more granular PRs over bigger ones. However, I could pull the changes from Pam/Nathan's fork and create a PR on our fork for all the refactoring efforts together. 

Thoughts?

**Comment by chinaowl** [comment]
I might be misunderstanding, but is that different from pushing your changes to Pam/Nathan's branch and then submitting that branch as a PR to the 350.org people?

Also, after looking at the changes in the `refactor` branch, I think it might be good to get all of this refactored code merged first before doing any new work (reversing my previous statement). But I'm not sure how the 350.org developers feel about that.

Let's hold off until we have more information. I think Miguel is going to schedule something for Thursday, hope you can make it!

**Comment by tainacaetano** [comment]
This branch got outdated and the value of figuring it out looks too small to be worth it. I'll be closing this PR and will come back with this sort of refactoring as part of feature implementation in the future.

**Pull request closed without merging**
